sudo: required
language: node_js
node_js:
- '7.7.1'
services:
- docker
before_install:
- sudo service postgresql stop
- docker-compose up -d
- docker ps -a
before_script:
- npm install -g gulp
- gulp selenium-install
- "./node_modules/db-migrate/bin/db-migrate up"
script:
- gulp test
- gulp test-integration
- gulp test-functional
after_success:
- .travis/deploy.sh
